# Generated by Django 5.2.6 on 2025-10-31 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_inscricao_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'virtual'), ('hibrido', 'Híbrido')], default='presencial', max_length=20),
        ),
    ]
