# Generated by Django 5.2.6 on 2025-10-31 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_organizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='core.organizador'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
